package main;

import java.awt.event.KeyEvent;


public final class FormPembayaran extends javax.swing.JFrame {

    hitunghitung hit = new hitunghitung();
    public double saldo = 1234567;
    
    public FormPembayaran() {
        initComponents();
        
        opPulsa.addItem("PILIH");
        opPulsa.addItem("Telkomsel");
        opPulsa.addItem("Tri");
        opPulsa.addItem("Smartfren");
        opPulsa.addItem("XL");
        opPulsa.addItem("AXIS");
        opPulsa.addItem("INDOSAT");
        
        tSaldo.setText("Rp. "+saldo);
        hit.setSaldo(saldo);
        
        nonaktif();
    }
    
    void nonaktif() {
        tSaldo.setEnabled(false);
        tHarga.setEnabled(false);
        tPPN.setEnabled(false);
        tTotal.setEnabled(false);
        inputPulsa.setEnabled(false);
    }
    
    void eksekusi() {
        hit.cekPulsa();
        hit.cekOperator();

        tHarga.setText(Double.toString(hit.getHarga()));
        tPPN.setText(Double.toString(hit.getPajak()));
        tTotal.setText(Double.toString(hit.getTotal()));
        inputPulsa.setEnabled(false);
    }
    
    void updateBiayaAdm() {
        switch (opPulsa.getSelectedItem().toString().toLowerCase()) {
            case "telkomsel":
                jLabel8.setText("Rp. 6000");
                break;
            case "tri":
                jLabel8.setText("Rp. 5000");
                break;
            case "smartfren":
                jLabel8.setText("Rp. 3000");
                break;
            case "xl":
                jLabel8.setText("Rp. 4000");
                break;
            case "axis":
                jLabel8.setText("Rp. 1000");
                break;
            case "indosat":
                jLabel8.setText("Rp. 2000");
                break;
            default:
                jLabel8.setText("Rp. 0");
                break;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pulsa = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        opPulsa = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tSaldo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tHarga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tPPN = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tTotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        pulsa5K = new javax.swing.JRadioButton();
        pulsa10K = new javax.swing.JRadioButton();
        pulsa15K = new javax.swing.JRadioButton();
        pulsa20K = new javax.swing.JRadioButton();
        pulsa25K = new javax.swing.JRadioButton();
        pulsa50K = new javax.swing.JRadioButton();
        pulsa100K = new javax.swing.JRadioButton();
        pulsaOther = new javax.swing.JRadioButton();
        inputPulsa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bProses = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Program Pembelian Pulsa");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 19)); // NOI18N
        jLabel1.setText("PROGRAM");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 19)); // NOI18N
        jLabel2.setText("PEMBELIAN PULSA");

        opPulsa.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        opPulsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opPulsaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel3.setText("Pilih operator");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel4.setText("Saldo");

        tSaldo.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel5.setText("Harga");

        tHarga.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel6.setText("PPN  10%");

        tPPN.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel7.setText("Total");

        tTotal.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        tTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTotalActionPerformed(evt);
            }
        });

        jButton1.setText("+");

        pulsa.add(pulsa5K);
        pulsa5K.setText("5000");
        pulsa5K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsa5KActionPerformed(evt);
            }
        });

        pulsa.add(pulsa10K);
        pulsa10K.setText("10000");
        pulsa10K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsa10KActionPerformed(evt);
            }
        });

        pulsa.add(pulsa15K);
        pulsa15K.setText("15000");
        pulsa15K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsa15KActionPerformed(evt);
            }
        });

        pulsa.add(pulsa20K);
        pulsa20K.setText("20000");
        pulsa20K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsa20KActionPerformed(evt);
            }
        });

        pulsa.add(pulsa25K);
        pulsa25K.setText("25000");
        pulsa25K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsa25KActionPerformed(evt);
            }
        });

        pulsa.add(pulsa50K);
        pulsa50K.setText("50000");
        pulsa50K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsa50KActionPerformed(evt);
            }
        });

        pulsa.add(pulsa100K);
        pulsa100K.setText("100000");
        pulsa100K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsa100KActionPerformed(evt);
            }
        });

        pulsa.add(pulsaOther);
        pulsaOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsaOtherActionPerformed(evt);
            }
        });

        inputPulsa.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        inputPulsa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputPulsaKeyPressed(evt);
            }
        });

        jLabel8.setText("Rp. 0");

        bProses.setText("Proses");
        bProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProsesActionPerformed(evt);
            }
        });

        bKeluar.setText("Keluar");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pulsa5K)
                                    .addComponent(pulsa10K))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pulsa15K)
                                    .addComponent(pulsa20K))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pulsa25K)
                                    .addComponent(pulsa50K))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pulsa100K)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pulsaOther)
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(inputPulsa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tPPN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bProses, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(102, 102, 102)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(tSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton1))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(opPulsa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(74, 74, 74)
                                    .addComponent(jLabel2))))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(opPulsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pulsa5K)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pulsa10K))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pulsa15K)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pulsa20K))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pulsa25K)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pulsa50K)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pulsa100K)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pulsaOther)
                            .addComponent(inputPulsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(bProses, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(bKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tPPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTotalActionPerformed

    private void opPulsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opPulsaActionPerformed
        String operator = opPulsa.getSelectedItem().toString();
        hit.setOperator(operator);
        eksekusi();
        updateBiayaAdm();
    }//GEN-LAST:event_opPulsaActionPerformed

    private void pulsa5KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsa5KActionPerformed
        if (pulsa5K.isSelected()) {
            hit.setPulsa("5K");
            eksekusi();
        } else {
            hit.setPulsa("0");
        }
        
    }//GEN-LAST:event_pulsa5KActionPerformed

    private void pulsa10KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsa10KActionPerformed
        hit.setPulsa("10K");
        eksekusi();
    }//GEN-LAST:event_pulsa10KActionPerformed

    private void pulsa15KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsa15KActionPerformed
        hit.setPulsa("15K");
        eksekusi();
    }//GEN-LAST:event_pulsa15KActionPerformed

    private void pulsa20KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsa20KActionPerformed
        hit.setPulsa("20K");
        eksekusi();
    }//GEN-LAST:event_pulsa20KActionPerformed

    private void pulsa25KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsa25KActionPerformed
        hit.setPulsa("25K");
        eksekusi();
    }//GEN-LAST:event_pulsa25KActionPerformed

    private void pulsa50KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsa50KActionPerformed
        hit.setPulsa("50K");
        eksekusi();
    }//GEN-LAST:event_pulsa50KActionPerformed

    private void pulsa100KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsa100KActionPerformed
        hit.setPulsa("100K");
        eksekusi();
    }//GEN-LAST:event_pulsa100KActionPerformed

    private void pulsaOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsaOtherActionPerformed
        hit.setPulsa("0K");
        eksekusi();
        inputPulsa.setEnabled(true);
        inputPulsa.requestFocus();
    }//GEN-LAST:event_pulsaOtherActionPerformed

    private void inputPulsaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputPulsaKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            double harga = Double.parseDouble(inputPulsa.getText());
            
            hit.setHarga(harga);
            hit.cekOperator();
            tHarga.setText(Double.toString(hit.getHarga()));
            tPPN.setText(Double.toString(hit.getPajak()));
            tTotal.setText(Double.toString(hit.getTotal()));
        }
    }//GEN-LAST:event_inputPulsaKeyPressed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bKeluarActionPerformed

    private void bProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProsesActionPerformed
        // tambah sendiri lah cape
        
    }//GEN-LAST:event_bProsesActionPerformed

    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bProses;
    private javax.swing.JTextField inputPulsa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> opPulsa;
    private javax.swing.ButtonGroup pulsa;
    private javax.swing.JRadioButton pulsa100K;
    private javax.swing.JRadioButton pulsa10K;
    private javax.swing.JRadioButton pulsa15K;
    private javax.swing.JRadioButton pulsa20K;
    private javax.swing.JRadioButton pulsa25K;
    private javax.swing.JRadioButton pulsa50K;
    private javax.swing.JRadioButton pulsa5K;
    private javax.swing.JRadioButton pulsaOther;
    private javax.swing.JTextField tHarga;
    private javax.swing.JTextField tPPN;
    private javax.swing.JTextField tSaldo;
    private javax.swing.JTextField tTotal;
    // End of variables declaration//GEN-END:variables

}
